### PR TITLE
Fix language translation for Kha and Zxx

### LINKED ISSUE #22: BMM Uploader - Language Khasi naming wrong
The language name Khasi is shown with its ISO code:

image

Please translate "kha" with [Khasi](https://en.wikipedia.org/wiki/Khasi_language).

### PR DESCRIPTION
**Pull request by KillerX**
Fixes #22

### CODE REVIEW

File: frontend/components/LanguageSelector.vue [hunk 1]
```diff
@@ -33,6 +33,15 @@ watch(
 const languageDisplay = (l: string) => {
     if (typeof Intl.DisplayNames !== "undefined") {
         const dn = new Intl.DisplayNames(["en"], { type: "language" });
+		let name = dn.of(l);
+
+		// Chorome doesn't support "hka"
```
Comment (sifferhans) [inline frontend/components/LanguageSelector.vue:38]: typo

**Review by sifferhans — APPROVED** [review]

File: frontend/components/LanguageSelector.vue (hunk 1 above)
Comment (KillerX) [inline frontend/components/LanguageSelector.vue:38]:
```suggestion
		// Chrome doesn't support "kha"
```
